# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermo', '0002_auto_20171116_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='endingTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='startingTime',
            field=models.TimeField(),
        ),
    ]
