# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermo', '0004_timeinterval_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('presence', models.BooleanField(default=0)),
            ],
        ),
    ]
